apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: irc-proxy
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: pod-irc-bot
status:
  loadBalancer: {}
