= PodIRCBot - A modular, containerized, IRC Bot

== What is it?

_PodIRCBot_ is an IRC bot that runs in a kubernetes pod. Each different that
the bot provides, such as quotes of the day and event planning, are performed
in their own containers, independent of one another. The containers
gets IRC messages and events via standard input, and responds by writing
to standard output.

== Getting Started

First, create your services by running `./create-service.sh`, following the instructions in
the template's README.

Then to run your service, use one of the two methods:

=== Docker Compose/Podman Compose

Run `./docker-compose.sh`.

=== Openshift

. `oc login` into your OpenShift account or into Red Hat's Code Ready Containers.

. `oc new-project YOUR_PROJECT_NAME_HERE`

. `./install.sh`; your IRC bot will be ready when the script finishes.

== Components

. *IRCProxy* - connects to the IRC server and forwards messages from
the server to each service as JSON, and forwards commands from each service
to the IRC server.
